config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'categories#index'
  get 'welcome', to: 'pages#index'

  get 'categories', to: 'categories#index'
  get '/products/:id', to: 'products#show', as: 'product'
  get '/products', to: 'products#index', as: 'products'

  # Terms of use and privacy policy
  get '/terms_of_use', to: 'legal_aspects#terms_of_use', as: 'terms'
  get '/privacy_policy', to: 'legal_aspects#privacy_policy', as: 'privacy'


  # Cart and order
  resources :order_items
  resource :carts, only: [:show]

  # Payment by PayPal
  post '/createpayment', to: 'carts#createpayment'
  post '/executepayment', to: 'carts#executepayment'

  resources :categories, only: [:index] do
    resources :products, only: [:index]
  end
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    #@categories = Category.all
    @categories = Category.joins(:products)
                      .select('categories.*, count(products.id) as products_count')
                      .group('categories.id')
                      .order(:title)

    @top_viewed = Product.order('views DESC').first(10)
  end


end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/views/categories/index.html.erb
<div class="container padding-top">
  <section>
    <div class="container">
      <div class="row no-gutters">
        <div class="col-lg-9 offset-lg-5-24">
          <nav class="navbar navbar-expand-lg navbar-light">
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#main_nav" aria-controls="main_nav" aria-expanded="false" aria-label="Toggle navigation">
              <span class="navbar-toggler-icon"></span>
            </button>
            <div class="collapse navbar-collapse" id="main_nav">
              <ul class="navbar-nav">
                <li class="nav-item">
                  <%= link_to 'All products', {:controller => "products", :action => :index}, :class => "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'New arrival', {:controller => "products", :action => :index, :select_param => 'created_at DESC'}, :class => "nav-link" %>
                </li>
                <li class="nav-item">
                  <%= link_to 'Populars', {:controller => "products", :action => :index, :select_param => 'views DESC'}, :class => "nav-link" %>
                </li>
              </ul>
            </div> <!-- collapse .// -->
          </nav>
        </div> <!-- col.// -->
      </div> <!-- row.// -->
    </div> <!-- container .// -->
  </section>

  <!-- ========================= SECTION MAIN ========================= -->
  <section class="section-main">
    <div class="container">
      <div class="row no-gutters border border-top-0 bg-white">
        <aside class="col-lg-5-24">
          <nav>
            <div class="title-category bg-secondary white d-none d-lg-block" style="margin-top:-53px">
              <span>Categories (<%= @categories.length %>)</span>
            </div>
            <ul class="menu-category">
              <% @categories.first(6).each do |category| %>
                <li>
                  <%= link_to category_products_path(category) do %>
                    <%= category.title %>
                  <% end %>

                </li>
              <% end %>

              <% if @categories.length > 6 %>
                <li class="has-submenu"><a href="#">More category <i class="icon-arrow-right pull-right"></i></a>
                  <ul class="submenu">
                    <% @categories[6..].each do |category| %>
                      <li>
                        <%= link_to category_products_path(category) do %>
                          <%= category.title %>
                          <span class="float-right badge badge-secondary round"><%= category.products.count %></span>
                        <% end %>
                      </li>
                    <% end %>

                  </ul>
                </li>
              <% end %>
            </ul>
          </nav>
        </aside> <!-- col.// -->
        <main class="col-lg-19-24">
          <!-- ========= intro aside ========= -->
          <div class="row no-gutters">
            <div class="col-lg-9 col-md-8">
              <!-- ================= main slide ================= -->

              <div class="owl-init slider-main owl-carousel" data-items="1" data-margin="1" data-nav="true" data-dots="false">
                <div class="item-slide">
                  <%= link_to image_tag('banners/game'), category_products_path(2) %>
                </div>
                <div class="item-slide">
                  <%= link_to image_tag('banners/harrypoter'), category_products_path(1) %>
                </div>
                <div class="item-slide">
                  <%= link_to image_tag('banners/starwars'), category_products_path(3) %>
                </div>
              </div>

              <!-- ============== main slidesow .end // ============= -->
            </div> <!-- col.// -->
            <div class="col-lg-3 col-md-4">
              <ul class="list-group list-group-flush">
                <li class="list-group-item">
                  <h6>The cheapest T-shorts</h6>
                  <%= link_to 'Show', {:controller => "products", :action => :index, :select_param => 'price ASC', :class => "btn btn-primary btn-sm btn-round"}  %>
                </li>
                <li class="list-group-item">
                  <h6>Most expensive T-shorts</h6>
                  <%= link_to 'Show', {:controller => "products", :action => :index, :select_param => 'price DESC', :class => "btn btn-primary btn-sm btn-round"}  %>
                </li>
              </ul>
            </div> <!-- col.// -->
          </div> <!-- row.// -->
          <!-- ======== intro aside ========= .// -->
        </main> <!-- col.// -->
      </div> <!-- row.// -->
    </div> <!-- container .//  -->
  </section>

  <h4 class="title-text">Top viewed T-shorts</h4>
  <!-- ============== owl slide items  ============= -->

  <div class="owl-carousel owl-init slide-items" data-items="5" data-margin="20" data-dots="true" data-nav="true">
    <% @top_viewed.each do |p| %>
      <div class="item-slide">
        <figure class="card card-product">

          <div class="img-wrap"><%= link_to(image_tag(p.image), product_path(p), :alt => "Avatar", :style => "width:100%") %></div>
          <figcaption class="info-wrap">
            <h4 class="title text-nowrap"><%= p.title %></h4>
            <p class="desc"><%= truncate(p.description, length: 60) %></p>
            <div class="rating-wrap">
              <div class="label-rating"><%= p.views %> views</div>
            </div> <!-- rating-wrap.// -->
          </figcaption>
          <div class="bottom-wrap">
            <%= link_to 'Order', product_path(p), :class => "btn btn-sm btn-primary float-right" %>
            <div class="price-wrap h5">
              <span class="price-new"><%= number_to_currency p.price %></span>
            </div> <!-- price-wrap.// -->
          </div> <!-- bottom-wrap.// -->
        </figure>
      </div>
    <% end %>
  </div>
  <!-- ============== owl slide items .end // ============= -->
</div>