config/routes.rb
Rails.application.routes.draw do
  devise_for :users, controllers: {
      registrations: 'registrations'
  }
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  root 'categories#index'
  get 'welcome', to: 'pages#index'

  get 'categories', to: 'categories#index'
  get '/products/:id', to: 'products#show', as: 'product'
  get '/products', to: 'products#index', as: 'products'

  # Terms of use and privacy policy
  get '/terms_of_use', to: 'legal_aspects#terms_of_use', as: 'terms'
  get '/privacy_policy', to: 'legal_aspects#privacy_policy', as: 'privacy'


  # Cart and order
  resources :order_items
  resource :carts, only: [:show]

  # Payment by PayPal
  post '/createpayment', to: 'carts#createpayment'
  post '/executepayment', to: 'carts#executepayment'

  resources :categories, only: [:index] do
    resources :products, only: [:index]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :products
end

app/models/order.rb
class Order < ApplicationRecord
  has_many :order_items
  before_save :set_subtotal

  public

  def update_user(user_id)
    update_attribute(:user_id, user_id)
  end

  def update_status_paid
    update_attribute(:is_paid, true)
  end


  def subtotal
    order_items.collect {|order_item| order_item.valid? ? (order_item.unit_price * order_item.quantity) : 0}.sum
  end

  private

  def set_subtotal
    self[:subtotal] = subtotal
  end

end

app/models/order_item.rb
class OrderItem < ApplicationRecord
  belongs_to :order
  belongs_to :product

  before_save :set_unit_price
  before_save :set_total_price

  def unit_price
    if persisted?
      self[:unit_price]
    else
      product.price
    end
  end

  def total_price
    unit_price * quantity
  end

  private

  def set_unit_price
    self[:unit_price] = unit_price
  end

  def set_total_price
    self[:total_price] = quantity * set_unit_price
  end
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :category
  has_many :order_items

  def self.search(search)
    if search
      where("title LIKE ?", "%#{search}%")
    else
      all
    end
  end
end

app/models/user.rb
class User < ApplicationRecord

  has_many :orders
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  include ApplicationHelper

  def after_sign_in_path_for(resource)
    stored_location_for(resource) || root_path
  end
end

app/controllers/carts_controller.rb
# frozen_string_literal: true

class CartsController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :set_paypaltoken, only: %i[createpayment executepayment]

  def show
    @order_items = current_order.order_items
  end

  def set_paypaltoken
    @paypaltoken = 'A21AAHKfz6KphCLVSYhk5eYQDbaEjE4gGDfw7qlT7CEctRKKyq_ueoPGm5hU6aJFRVNuS7xIG26mIBoXa09YNSYFkNgaJM-pQ'
  end

  def home; end

  def createpayment
    @order = current_order
    @response = HTTParty.post('https://api.sandbox.paypal.com/v1/payments/payment',
                              headers: { 'Content-Type' => 'application/json',
                                         'Authorization' => "Bearer #{@paypaltoken}" },
                              body: { intent: 'sale',
                                      redirect_urls: {
                                        'return_url' => 'http://localhost:3000/',
                                        'cancel_url' => 'http://localhost:3000/'
                                      },
                                      payer: { 'payment_method' => 'paypal' },
                                      transactions: [
                                        { 'amount' => {
                                          'total' => @order.subtotal,
                                          'currency' => 'EUR'
                                        } }
                                      ] }.to_json, debug_output: Rails.logger)
    render json: {
      id: (@response['id']).to_s
    }.to_json
  end

  def executepayment
    @response = HTTParty.post("https://api.sandbox.paypal.com/v1/payments/payment/#{params[:paymentID]}/execute/",
                              headers: { 'Content-Type' => 'application/json',
                                         'Authorization' => "Bearer #{@paypaltoken}" },
                              body: { payer_id: params[:payerID].to_s }.to_json, debug_output: Rails.logger)

    @order = current_order
    @order.update_user(current_user.id)

    # update payment status
    body = JSON.parse(@response.body)
    state = body['state']
    if state.to_s == 'approved'
      @order.update_status_paid
    end

    # Clean order and create new order
    session[:order_id] = nil

  end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    #@categories = Category.all
    @categories = Category.joins(:products)
                      .select('categories.*, count(products.id) as products_count')
                      .group('categories.id')
                      .order(:title)

    @top_viewed = Product.order('views DESC').first(10)
  end


end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

  def index
    if params[:category_id]
      @category = Category.find(params[:category_id])
      @products = @category.products.order(:title)
    elsif params.has_key?(:select_param)
      @select_param = params[:select_param]
      @products = Product.order("#{@select_param}").first(10)
      @type = param_type(@select_param)
    elsif params[:search]
      @products = Product.search(params[:search]).order("created_at DESC")
      @type = 'Products'
    else
      @products = Product.all
      @type = 'All products'
    end
    @partial = params[:view] || "/layouts/grid" || "/layouts/list" # "grid", "list", etc.
  end

  def show
    @product = Product.find(params[:id])
    if session[:products_views]
      unless session[:products_views].include?(params[:id])
        session[:products_views].push(params[:id])
        @product.update_attribute(:views, @product.views + 1)
      end
      @category = Category.find @product.category_id
      @order_item = current_order.order_items.new
    end
  end

  def param_type(type)
    case type
    when 'created_at DESC'
      "New arrival"
    when 'views DESC'
      'Populars'
    when 'price ASC'
      'Cheapest'
    when 'price DESC'
      'Expensive'
    else
      # type code here
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper

  def current_order
    (session[:products_views] ||= [])
    if !session[:order_id].nil?
      Order.find(session[:order_id])
    else
      Order.new
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/legal_aspects_helper.rb
module LegalAspectsHelper
end

app/helpers/order_items_helper.rb
module OrderItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/_grid.html.erb
<div class="row">
  <% @products.each do |product| %>
    <div class="col-md-4">
      <figure class="card card-product">
        <div class="img-wrap">  <%= link_to(image_tag(product.image), product_path(product), :class => "img-md") %></div>
        <figcaption class="info-wrap">
          <h4 class="title"><%= product.title %></h4>
          <p class="desc"><%= truncate(product.description, length: 100) %></p>
          <div class="rating-wrap">
            <ul class="rating-stars">
              <li style="width:80%" class="stars-active">
                <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i>
              </li>
              <li>
                <i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i><i class="fa fa-star"></i>
              </li>
            </ul>
            <div class="label-rating"><%= product.views %> views</div>
            <div class="label-rating"><%= product.orders %> orders</div>
          </div> <!-- rating-wrap.// -->
        </figcaption>
        <div class="bottom-wrap">
          <%= link_to 'Order Now', product_path(product), :class => "btn btn-sm btn-primary float-right" %>
          <div class="price-wrap h5">
            <span class="price-new"><%= number_to_currency product.price %></span>
          </div> <!-- price-wrap.// -->
        </div> <!-- bottom-wrap.// -->
      </figure>
    </div> <!-- col // -->
  <% end %>
</div>

app/views/layouts/_list.html.erb
<div class="card">
  <% @products.each do |product| %>
    <article class="itemlist">
      <div class="row row-sm">
        <aside class="col-sm-3">
          <div class="img-wrap">  <%= link_to(image_tag(product.image, size: "148x160"), product_path(product), :class => "img-md") %></div>
        </aside> <!-- col.// -->
        <div class="col-sm-6">
          <div class="text-wrap">
            <h4 class="title"> <%= product.title %></h4>
            <p> <%= product.description %> </p>
            <p class="rating-wrap my-0 text-muted">
              <span class="label-rating"><%= product.views %> views</span>
              <span class="label-rating"><%= product.orders %> orders</span>
            </p> <!-- rating-wrap.// -->
          </div> <!-- text-wrap.// -->
        </div> <!-- col.// -->
        <aside class="col-sm-3">
          <div class="border-left pl-3">
            <div class="price-wrap">
              <span class="h3 price"> <%= number_to_currency product.price %> </span>
            </div> <!-- info-price-detail // -->
            <p class="text-success">Free shipping</p>
            <p>
              <%= link_to 'Order Now', product_path(product), :class => "btn btn-primary " %>
            </p>
          </div> <!-- action-wrap.// -->
        </aside> <!-- col.// -->
      </div> <!-- row.// -->
    </article> <!-- itemlist.// -->
  <% end %>
</div>

app/views/layouts/_shopping_basket.html.erb
<%= link_to carts_path, class: "widget-header border-left pl-3 ml-3" do %>
  <div class="icontext">
    <div class="icon-wrap icon-sm round border"><i class="fa fa-shopping-cart"></i></div>
  </div>
  <span class="badge badge-pill badge-danger notify"><%= current_order.order_items.size %></span>
<% end %>

app/views/layouts/_user_widget_status.html.erb
<% if user_signed_in? %>
  <div class="widget-header">
    <div class="icontext">
      <div class="text-wrap dropdown">
        <small><%= "Welcome " + current_user.name %></small>
        <a href="#" class="b" data-toggle="dropdown" data-offset="20,10" aria-expanded="false">
          My account <i class="fa fa-caret-down"></i>
        </a>
        <div class="dropdown-menu">
          <%= link_to 'Editar perfil', edit_user_registration_path, class: "dropdown-item" %>
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
        </div>
      </div> <!-- text-wrap.// -->
    </div>
  </div>
<% else %>
  <div class="widget-header">
    <small class="title text-muted">Welcome guest!</small>
    <div>
      <%= link_to "Login in", new_user_session_path, class: "dark-transp", role: "button" %> | </span>
      <%= link_to "Register", new_user_registration_path, class: "dark-transp", role: "button" %>
    </div>
  </div>
<% end %>

<div class="active cart"><%= render 'layouts/shopping_basket' %></div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ECommerce</title>
  <%= csrf_meta_tags %>

  <meta name="viewport" content="width=device-width, initial-scale=1">
  <%= stylesheet_link_tag 'https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css' %>
  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body class="<%= yield (:body_class) %>">

<header class="section-header">
  <nav class="navbar navbar-top navbar-expand-lg navbar-dark bg-secondary">
    <div class="container">
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarTop" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarTop">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="#"> <i class="fa fa-phone"></i> Call us: +34 673 123 342 </a>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"> USD </a>
            <ul class="dropdown-menu small">
              <li><a class="dropdown-item" href="#">EUR</a></li>
              <li><a class="dropdown-item" href="#">USD</a></li>
            </ul>
          </li>
          <li class="nav-item dropdown">
            <a href="#" class="nav-link dropdown-toggle" data-toggle="dropdown"> Language </a>
            <ul class="dropdown-menu small">
              <li><a class="dropdown-item" href="#">English</a></li>
              <li><a class="dropdown-item" href="#">Spanish</a></li>
              <li><a class="dropdown-item" href="#">Catalan </a></li>
            </ul>
          </li>
        </ul>
        <ul class="navbar-nav">
          <li><%= link_to "Shop", categories_path, class: "nav-link" %></li>
          <li><%= link_to "About us", welcome_path, class: "nav-link" %></li>
        </ul> <!-- list-inline //  -->
      </div> <!-- navbar-collapse .// -->
    </div> <!-- container //  -->
  </nav>

  <section class="header-main">
    <div class="container">
      <div class="row align-items-lg-start">
        <div class="col-lg-5-24 col-sm-5 col-4">
          <div class="brand-wrap">
            <b> - </b><%=link_to image_tag(('logo'), :class => 'logo'), root_path %>
          </div> <!-- brand-wrap.// -->
        </div>

        <!-- search -->
        <div class="col-lg-13-24 col-sm-12 order-3 order-lg-2">
          <%= form_tag products_path, :method => 'get', :autocomplete => 'off' do %>
            <div class="input-group w-100">
              <%= text_field_tag :search, params[:search], :style => 'width:60%;', :class => 'form-control', :placeholder => 'Search' %>
              <%= button_tag '', :class => 'btn btn-primary' do %>
                <i class="fa fa-search"></i>
              <% end %>
            </div>
          <% end %>
        </div>

        <div class="col-lg-6-24 col-sm-7 col-8  order-3 order-lg-3">
          <div class="d-flex justify-content-end">
            <%= render '/layouts/user_widget_status' %>
          </div> <!-- widgets-wrap.// -->
        </div> <!-- col.// -->

      </div> <!-- row.// -->
    </div> <!-- container.// -->
  </section> <!-- header-main .// -->
</header>

<% if flash[:notice] %>
  <div class="alert alert-success" role="alert">
    <%= notice %>
  </div>
<% end %>
<% if flash[:alert] %>
  <div class="alert alert-danger" role="alert">
    <%= alert %>
  </div>
<% end %>


<%= yield %>


<footer class="section-footer bg-secondary" style="margin-top: 10%;">
  <div class="container">
    <section class="footer-top padding-top">
      <div class="row">
        <aside class="col-sm-3 col-md-3 white">
          <h5 class="title">Legal Aspects</h5>
          <ul class="list-unstyled">
            <li><%=link_to " Privacy Policy ", privacy_path %></li>
            <li><%=link_to " Terms of Use ", terms_path %></li>

          </ul>
        </aside>
        <aside class="col-sm-3  col-md-3 white">
          <h5 class="title">My Account</h5>
          <ul class="list-unstyled">
            <li><%=link_to " User Login ", new_user_session_path %></li>
            <li><%=link_to " User Register ", new_user_registration_path%></li>
            <li><%=link_to " Account Setting ", edit_user_registration_path%></li>
            <li><a href="#"> My Orders </a></li>
          </ul>
        </aside>
        <aside class="col-sm-3  col-md-3 white">
          <h5 class="title">About</h5>
          <ul class="list-unstyled">
            <li><%=link_to " Our history ", welcome_path  %></li>
            <li><%=link_to " How to buy ", welcome_path  %></li>
            <li><%=link_to " Delivery and payment ", welcome_path  %></li>
          </ul>
        </aside>
        <aside class="col-sm-3">
          <article class="white">
            <h5 class="title">Contacts</h5>
            <p>
              <strong>Phone: </strong> +34 673 123 342 <br>
              <strong>Fax:</strong> +34 673 123 342
            </p>

            <div class="btn-group white">
              <a class="btn btn-facebook" title="Facebook" target="_blank" href="#"><i class="fa fa-facebook-f  fa-fw"></i></a>
              <a class="btn btn-instagram" title="Instagram" target="_blank" href="#"><i class="fa fa-instagram  fa-fw"></i></a>
              <a class="btn btn-youtube" title="Youtube" target="_blank" href="#"><i class="fa fa-youtube  fa-fw"></i></a>
              <a class="btn btn-twitter" title="Twitter" target="_blank" href="#"><i class="fa fa-twitter  fa-fw"></i></a>
            </div>
          </article>
        </aside>
      </div> <!-- row.// -->
      <br>
    </section>
  </div><!-- //container -->
</footer>


<script>
    window.setTimeout(function () {
        $(".alert").fadeTo(500, 0).slideUp(500, function () {
            $(this).remove();
        });
    }, 4000);
</script>

<script>
    var products = <%= Product.all.to_json.html_safe %>;
    var titles = new Array(products.length)
    for (i = 0; i < products.length; i++) {
        titles[i] = products[i].title;
    }
    autocomplete(document.getElementById("search"), titles);
</script>

</body>
</html>

app/views/pages/home.html.erb
<!DOCTYPE HTML>
<html lang="en">
<head>
  <meta charset="utf-8">
  <title>UI KIT - Marketplace and Ecommerce html template</title>


  <!-- Font awesome 5 -->
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">


</head>
<body class="relative" data-spy="scroll" data-target=".navbar-landing">
<header class="section-header">
  <nav class="navbar navbar-landing navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
      <a class="navbar-brand mr-auto" href="#"> <img class="logo" src="/assets/logo-white.png"> LOGO</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbar1">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbar1">
        <ul class="navbar-nav ml-auto">
          <li class="nav-item">
            <a class="nav-link page-scroll" href="#intro">Intro</a>
          </li>
          <li class="nav-item">
            <a class="nav-link page-scroll" href="#features">Features</a>
          </li>
          <li class="nav-item">
            <a class="nav-link page-scroll" href="#content">Content</a>
          </li>
          <li class="nav-item">
            <a class="nav-link page-scroll" href="#more">More info</a>
          </li>
          <li class="nav-item">
            <%= link_to "Tienda", {controller: "products", action: "index"}, class: "nav-link" %>
          </li>
        </ul>
      </div>
    </div> <!-- container //  -->
  </nav>
</header> <!-- section-header.// -->

<!-- ========================= SECTION INTRO ========================= -->
<section id="intro" class="section-intro bg-secondary pt-5">
  <div class="container">
    <div class="row d-flex" style="min-height:600px;">
      <div class="col-sm-6 d-flex align-items-center">
        <header class="intro-wrap text-white">
          <h2 class="display-3"> Amazing place for hero title </h2>
          <p class="lead">Bootstrap ecommerce is more then template - also framework. <br> It is modern and fully
            customizable websites, WebApp and Mobile template for Your Project</p>
          <a href="#" class="btn btn-warning">Download</a>
          <a href="#" class="btn btn-light">Learn more</a>
        </header>  <!-- intro-wrap .// -->
      </div> <!-- col.// -->
      <div class="col-sm-6 text-right">
        <img src="/assets/items/comp.png" class="img-fluid my-5" width="500">
      </div> <!-- col.// -->
    </div> <!-- row.// -->
  </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION INTRO END// ========================= -->


<!-- ========================= SECTION FEATURES ========================= -->
<section id="features" class="section-features bg2 padding-y-lg">
  <div class="container">

    <header class="section-heading text-center">
      <h2 class="title-section">How it works </h2>
      <p class="lead"> Good sub heading this sounded nonsense to Alice </p>
    </header><!-- sect-heading -->

    <div class="row">
      <aside class="col-sm-4">
        <figure class="itembox text-center">
          <span class="icon-wrap icon-lg bg-secondary white"><i class="fa fa-gamepad"></i></span>
          <figcaption class="text-wrap">
            <h4 class="title">Sync across all devices</h4>
            <p>This sounded nonsense to Alice, so she said nothing, but set off at once toward the Red Queen. To her
              surprise.</p>
          </figcaption>
        </figure> <!-- iconbox // -->
      </aside> <!-- col.// -->
      <aside class="col-sm-4">
        <figure class="itembox text-center">
          <span class="icon-wrap icon-lg bg-secondary white"><i class="fa fa-heart"></i></span>
          <figcaption class="text-wrap">
            <h4 class="title">Easy to Customize</h4>
            <p>This sounded nonsense to Alice, so she said nothing, but set off at once toward the Red Queen. To her
              surprise. </p>
          </figcaption>
        </figure> <!-- iconbox // -->
      </aside> <!-- col.// -->
      <aside class="col-sm-4">
        <figure class="itembox text-center">
          <span class="icon-wrap icon-lg bg-secondary  white"><i class="fa fa-users"></i>	</span>
          <figcaption class="text-wrap">
            <h4 class="title">Unique Interface Design</h4>
            <p>This sounded nonsense to Alice, so she said nothing, but set off at once toward the Red Queen. To her
              surprise. </p>
          </figcaption>
        </figure> <!-- iconbox // -->
      </aside> <!-- col.// -->
    </div> <!-- row.// -->

    <p class="text-center">
      <br>
      <a href="#" class="btn btn-warning">Some action button</a>
    </p>

  </div><!-- container // -->
</section>
<!-- ========================= SECTION FEATURES END// ========================= -->

<!-- ========================= SECTION CONTENT  ========================= -->
<section id="content" class="section-content padding-y-lg">
  <div class="container">

    <header class="section-heading text-center">
      <h2 class="title-section">Section name</h2>
      <p class="lead"> Good sub heading this sounded nonsense to Alice </p>
    </header><!-- sect-heading -->

    <div class="row justify-content-center">
      <article class="col-md-6 text-center">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </article> <!-- col.// -->
    </div> <!-- row.// -->

  </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT  END// ========================= -->


<!-- ========================= SECTION CONTENT ASIDE ========================= -->
<section id="more" class="bg section-content padding-y-lg">
  <div class="container">

    <header class="section-heading text-center">
      <h2 class="title-section"> Another Section</h2>
      <p class="lead"> Good sub heading this sounded nonsense to Alice </p>
    </header><!-- sect-heading -->

    <div class="row justify-content-center">
      <article class="col-md-6 text-center">
        <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
          tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
        <p>Ut enim ad minim veniam,
          quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
          consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
          cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
          proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
      </article> <!-- col.// -->
    </div> <!-- row.// -->

  </div> <!-- container .//  -->
</section>
<!-- ========================= SECTION CONTENT ASIDE END// ========================= -->


<!-- ========================= FOOTER ========================= -->
<footer class="section-footer bg-dark white">
  <div class="container">
    <section class="footer-bottom row">
      <div class="col-sm-6">
        <p> Made with <3 <br> by Vosidiy M.</p>
      </div>
      <div class="col-sm-6">
        <p class="text-sm-right">
          Copyright &copy 2018 <br>
          <a href="http://bootstrap-ecommerce.com">Bootstrap-ecommerce UI kit</a>
        </p>
      </div>
    </section> <!-- //footer-top -->
  </div><!-- //container -->
</footer>
<!-- ========================= FOOTER END // ========================= -->


</body>